# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orkestra < Formula
  desc "Deterministic workflow orchestration engine — run complex workflows from YAML, locally or in CI."
  homepage "https://github.com/dszczyt/orkestra-releases"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dszczyt/orkestra-releases/releases/download/v0.1.0/orkestra_0.1.0_darwin_amd64.tar.gz"
      sha256 "d019f077d1906de96fa440f6cf43a226522c716c861b5f3b5cc1f5519662d264"

      define_method(:install) do
        bin.install "orkestra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dszczyt/orkestra-releases/releases/download/v0.1.0/orkestra_0.1.0_darwin_arm64.tar.gz"
      sha256 "f51cdec0e8e5246f44e6404c5ee7b5a8a2a64bd7365a41b6f4974c557d8e7d02"

      define_method(:install) do
        bin.install "orkestra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dszczyt/orkestra-releases/releases/download/v0.1.0/orkestra_0.1.0_linux_amd64.tar.gz"
      sha256 "c6e1e4825212493e7b246e4644a06e7eeb0c65a344d757677b167dd9ecfd5cac"
      define_method(:install) do
        bin.install "orkestra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dszczyt/orkestra-releases/releases/download/v0.1.0/orkestra_0.1.0_linux_arm64.tar.gz"
      sha256 "7148143f1e85f8afa0f5013d6a454e26a3e120a76aea8d66265b6a468d0802b3"
      define_method(:install) do
        bin.install "orkestra"
      end
    end
  end

  test do
    system "#{bin}/orkestra", "run", "--help"
  end
end
