# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orkestra < Formula
  desc "Deterministic workflow orchestration engine — run complex workflows from YAML, locally or in CI."
  homepage "https://github.com/dszczyt/orkestra-releases"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dszczyt/orkestra-releases/releases/download/v0.1.0/orkestra_0.1.0_darwin_amd64.tar.gz"
      sha256 "d30c04e22a00fa673802cf9e91b6e7c225fe33a1f755e598e223237d5b3003b1"

      define_method(:install) do
        bin.install "orkestra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dszczyt/orkestra-releases/releases/download/v0.1.0/orkestra_0.1.0_darwin_arm64.tar.gz"
      sha256 "0cfdc944dd57fe5ad3539433d83bc4aa0166c665796c67945f2aaa14b02c3188"

      define_method(:install) do
        bin.install "orkestra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dszczyt/orkestra-releases/releases/download/v0.1.0/orkestra_0.1.0_linux_amd64.tar.gz"
      sha256 "67e2d150209a6acd05ea7cd95f3926873d36a3e4248c4829a7bbe2df4d3b3537"
      define_method(:install) do
        bin.install "orkestra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dszczyt/orkestra-releases/releases/download/v0.1.0/orkestra_0.1.0_linux_arm64.tar.gz"
      sha256 "cb35891476f42c972d30befa8fe35ca42a3a1cc8c9df06a1fa2f7fde562872a7"
      define_method(:install) do
        bin.install "orkestra"
      end
    end
  end

  test do
    system "#{bin}/orkestra", "run", "--help"
  end
end
