# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orkestra < Formula
  desc "Deterministic workflow orchestration engine — run complex workflows from YAML, locally or in CI."
  homepage "https://github.com/dszczyt/orkestra-releases"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dszczyt/orkestra-releases/releases/download/v0.1.0/orkestra_0.1.0_darwin_amd64.tar.gz"
      sha256 "493c3d8579290b756df90cd0c6e9222aa02406afbd5d03aaa51d51a747d238c2"

      define_method(:install) do
        bin.install "orkestra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dszczyt/orkestra-releases/releases/download/v0.1.0/orkestra_0.1.0_darwin_arm64.tar.gz"
      sha256 "228241b2750a893fb6a14042249f489708231ad6e47145ff04167f12cba244cb"

      define_method(:install) do
        bin.install "orkestra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dszczyt/orkestra-releases/releases/download/v0.1.0/orkestra_0.1.0_linux_amd64.tar.gz"
      sha256 "e80f98822d035a52c6c391e57121540d62fc7cdb77826782ae9a0824ac373139"
      define_method(:install) do
        bin.install "orkestra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dszczyt/orkestra-releases/releases/download/v0.1.0/orkestra_0.1.0_linux_arm64.tar.gz"
      sha256 "eef119f15b0088a5fa2dc73f030917971932018622941fb2951cb178d95073e6"
      define_method(:install) do
        bin.install "orkestra"
      end
    end
  end

  test do
    system "#{bin}/orkestra", "run", "--help"
  end
end
